# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'MySwiftProduct' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MySwiftProduct
  source 'https://github.com/CocoaPods/Specs.git'
  
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'MJRefresh', '~> 3.1.14.1'
pod 'SnapKit'
  pod 'Kingfisher'
#tabbar样式
  pod 'ESTabBarController-swift'
#banner滚动图片
    pod 'FSPagerView'
    pod 'Moya'
#    pod 'HandyJSON', '~> 4.2.0'
   pod 'HandyJSON', '~> 5.0.2-beta'
    pod 'SwiftyJSON'
    # 分页
    pod 'DNSPageView'
    #跑马灯
    pod 'JXMarqueeView'
    #滚动页
    pod 'LTScrollView'
   
    #pod 'SkeletonView'
    #消息提示
    pod 'SwiftMessages'
    #pod 'YYKit'
    pod 'SVProgressHUD'
    #播放网络音频
    pod 'StreamingKit'
    #顶部分段选择器
    pod 'JXSegmentedView'
    #占位图第三方库
    pod 'DZNEmptyDataSet'
end
